### ISSUE TITLE
Mutex Lock Fails or TLS Handshake Never Completes

### ISSUE THREAD

**Issue by nuertey** [coisme/Hello-TLSSocket#2]
Hello,
Thanks for this sample code. I tried compiling and running it on my STM32 target and out of the box, I get a Mutex Lock Failed assertion. When I increased the "events.shared-stacksize" to 8192, the program seems to hang on "Starting TLS handshake with os.mbed.com".

I then set "tls-socket.debug-level" to 2 so that we get more information in the trace logs. That log file is attached. Any idea what could be going on? Let me know if you need further info.

Compiler : GCC_ARM version 7.3.1
Target : NUCLEO_F767ZI

**Out-of-the-Box Log 1 :** 

_"HelloTSLSocket, HTTPS example of TLSSocket
Connecting to network
Synchronizing time
Time set.
[INFO][TLSW]: mbedtls_ssl_config_defaults()
[INFO][TLSW]: mbedtls_ssl_conf_ca_chain()
[INFO][TLSW]: mbedtls_ssl_conf_rng()
[INFO][TLSW]: mbedtls_ssl_conf_authmode()
[INFO][TLSW]: mbedtls_ssl_setup()
[INFO][TLSW]: Starting TLS handshak

++ MbedOS Error Info ++
Error Status: 0x80020115 Code: 277 Module: 2
Error Message: Mutex lock failed
Location: 0x802AE0B
Error Value: 0xFFFFFFFC
Current Thread: Id: 0x2000F014 Entry: 0x802B23B StackSize: 0x1000 StackMem: 0x2000F058 SP: 0x2000FEB0 
For more info, visit: https://armmbed.github.io/mbedos-error/?error=0x80020115
-- MbedOS Error Info --"_

**Increased Stack Size Log 2 :**

_HelloTSLSocket, HTTPS example of TLSSocket
Connecting to network
Synchronizing time
Time set.
[INFO][TLSW]: mbedtls_ssl_config_defaults()
[INFO][TLSW]: mbedtls_ssl_conf_ca_chain()
[INFO][TLSW]: mbedtls_ssl_conf_rng()
[INFO][TLSW]: mbedtls_ssl_conf_authmode()
[INFO][TLSW]: mbedtls_ssl_setup()
[INFO][TLSW]: Starting TLS handshake with os.mbed.com_

[https://github.com/nuertey/RandomArtifacts/blob/master/TLSSocket_Log3.txt](url)

**Comment by coisme** [comment]
Hi @nuertey , thank you for reporting. Let me look into the issue.

**Comment by coisme** [comment]
@nuertey The main reason of the issue seems lack of memory. I changed the code to get memory from heap instead of stack, this is recommended. In addition, the server of Root CA Certificate changed. I updated. Please try again when you have time.

**Comment by coisme** [comment]
Hi @nuertey , I fixed the issue and tested on F767ZI. 

Here are changes:
- Allocate memory to TLSSocket instance from heap
- Update Root CA certificate
- Correct new line code in HTTP request from `\n` to `\r\n`

Please check if this works for you. 

FYI, Mbed OS 5.11 will be released soon and TLSSocket will be included in Mbed OS from 5.11. I'll update this example program once Mbed OS 5.11 is released.

**Comment by nuertey** [comment]
Hi @coisme ,
Thanks for the fixes. Good catch. I have updated to your latest and rerun the tests, first run with the code as provided and second run setting the TLS Socket debug log level. Both logs have been uploaded here : 

https://github.com/nuertey/RandomArtifacts/blob/master/TLSSocket_Log20181211-02:57:03.txt

Unfortunately it still doesn't work for me. The TLS handshake never seems to return. Hope the debug logs give a clue as to what could be going on this time. Perhaps the Root CA Certificate?  

Thanks for the headsup on Mbed OS 5.11 and its inclusion of the TLSSocket library.

**Comment by nuertey** [comment]
Also @coisme , does it matter if we set_root_ca_cert() **before** versus **after** calling open() on the socket?

**Comment by nuertey** [comment]
Aha! So @coisme , I tried the previous intuition of setting the root CA certificate **before** opening the socket and it works now. So you may want to update your code with that change. Thanks for the help. Here is my complete success logs :

HelloTSLSocket, HTTPS example of TLSSocket
Connecting to network
Synchronizing time
Time set.
[INFO][TLSW]: mbedtls_ssl_config_defaults()
[INFO][TLSW]: mbedtls_ssl_conf_ca_chain()
[INFO][TLSW]: mbedtls_ssl_conf_rng()
[INFO][TLSW]: mbedtls_ssl_conf_authmode()
[INFO][TLSW]: mbedtls_ssl_setup()
[INFO][TLSW]: Starting TLS handshake with os.mbed.com
[INFO][TLSW]: TLS connection to os.mbed.com established

[DBG ][TLSW]: Server certificate:
    cert. version     : 3
    serial number     : 0F:22:3C:45:F9:9B:25:DA:B5:A0:E9:E4:C3:F9:5F:9D
    issuer name       : C=US, O=Amazon, OU=Server CA 1B, CN=Amazon
    subject name      : CN=mbed.com
    issued  on        : 2018-03-16 00:00:00
    expires on        : 2019-04-16 12:00:00
    signed using      : RSA with SHA-256
    RSA key size      : 2048 bits
    basic constraints : CA=false
    subject alt name  : mbed.com, *.mbed.com, mbed.org, *.mbed.org
    key usage         : Digital Signature, Key Encipherment
    ext key usage     : TLS Web Server Authentication, TLS Web Client Authentication


[INFO][TLSW]: Certificate verification passed
Connected to os.mbed.com
socket_state_handler() next_state = 0
[DBG ][TLSW]: send 93
send(): GET /media/uploads/mbed_official/hello.txt HTTP/1.1
Host: os.mbed.com
Connection: close


socket_state_handler() next_state = 2
socket_state_handler() next_state = 2
recv() HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: max-age=36000
Content-Type: text/plain
Date: Tue, 11 Dec 2018 09:32:00 GMT
ETag: "5bf0036d-e"
Expires: Tue, 11 Dec 2018 19:32:00 GMT
Last-Modified: Sat, 17 Nov 2018 12:02:53 GMT
Server: nginx/1.15.3
Content-Length: 14
Connection: Close


socket_state_handler() next_state = 2
socket_state_handler() next_state = 2
recv() Hello world!

socket_state_handler() next_state = 3
[INFO][TLSW]: Closing TLS
connection closed! received total 315 bytes

HelloTSLSocket DONE.

**Comment by coisme** [comment]
Hi @nuertey , thank you for trying. Root CA certificate must be set before **connect()**. It can be set after **open()**.

In my environment, NUCLEO F767ZI + GCC_ARM, the program works as is. Here's log:

```
HelloTSLSocket, HTTPS example of TLSSocket
Connecting to network
Synchronizing time
Time set.
[INFO][TLSW]: mbedtls_ssl_config_defaults()
[INFO][TLSW]: mbedtls_ssl_conf_ca_chain()
[INFO][TLSW]: mbedtls_ssl_conf_rng()
[INFO][TLSW]: mbedtls_ssl_conf_authmode()
[INFO][TLSW]: mbedtls_ssl_setup()
[INFO][TLSW]: Starting TLS handshake with os.mbed.com
[INFO][TLSW]: TLS connection to os.mbed.com established

[DBG ][TLSW]: Server certificate:
    cert. version     : 3
    serial number     : 0F:22:3C:45:F9:9B:25:DA:B5:A0:E9:E4:C3:F9:5F:9D
    issuer name       : C=US, O=Amazon, OU=Server CA 1B, CN=Amazon
    subject name      : CN=mbed.com
    issued  on        : 2018-03-16 00:00:00
    expires on        : 2019-04-16 12:00:00
    signed using      : RSA with SHA-256
    RSA key size      : 2048 bits
    basic constraints : CA=false
    subject alt name  : mbed.com, *.mbed.com, mbed.org, *.mbed.org
    key usage         : Digital Signature, Key Encipherment
    ext key usage     : TLS Web Server Authentication, TLS Web Client Authentication


[INFO][TLSW]: Certificate verification passed
Connected to os.mbed.com
socket_state_handler() next_state = 0
[DBG ][TLSW]: send 93
send(): GET /media/uploads/mbed_official/hello.txt HTTP/1.1
Host: os.mbed.com
Connection: close


socket_state_handler() next_state = 2
recv() HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: max-age=36000
Content-Type: text/plain
Date: Wed, 12 Dec 2018 01:39:13 GMT
ETag: "5bf0036d-e"
Expires: Wed, 12 Dec 2018 11:39:13 GMT
Last-Modified: Sat, 17 Nov 2018 12:02:53 GMT
Server: nginx/1.15.3
Content-Length: 14
Connection: Close

Hello world!

socket_state_handler() next_state = 3
[INFO][TLSW]: Closing TLS
connection closed! received total 315 bytes
so
HelloTSLSlocket DONE.
loTSLSocket DONE.
) next_state = 4
```

`mbed ls` output:
```
$ mbed ls
Hello-TLSSocket (#35e7003e86b3)
|- TLSSocket (#723094a6ff84)
|- mbed-os (#6f338f8915d2)
`- ntp-client (#72a3f00ca7c1)
```

`arm-none-eabi-gcc --version` output:
```
arm-none-eabi-gcc (GNU Tools for ARM Embedded Processors 6-2017-q2-update) 6.3.1 20170620 (release) [ARM/embedded-6-branch revision 249437]
```

I've also tried GCC 7.3.1 and it worked. Hmm, what's the difference? I'm using macOS. Are you using Windows?

**Comment by nuertey** [comment]
Hi @coisme , 
That is indeed interesting. I am on Ubuntu 16.04 Linux. Maybe there is some particular quirk with my ISP/network connection?

Here are my equivalent commands to yours; all versions of the libraries seems to match :

```
uname -a
Linux PurpleOS 4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

```
mbed ls
[mbed] Working path "~/Workspace/Hello-TLSSocket" (library)
[mbed] Program path "~/Workspace/Hello-TLSSocket"
Hello-TLSSocket (#35e7003e86b3)
|- TLSSocket (#723094a6ff84)
|- mbed-os (#6f338f8915d2)
`- ntp-client (#72a3f00ca7c1)
```


```
./arm-none-eabi-gcc --version
arm-none-eabi-gcc (GNU Tools for Arm Embedded Processors 7-2018-q2-update) 7.3.1 20180622 (release) [ARM/embedded-7-branch revision 261907]
```

**Comment by nuertey** [comment]
Hello @coisme ,
I just noticed another small issue with the code. The socket allocated on the heap on line 122 is never released so that memory will be leaked. So we should deallocate that memory after line 145.
```
completed.wait_any(1);
delete socket;
```

**Comment by coisme** [comment]
Hi @nuertey , I'm trying building the program on Ubuntu. I can get result within a day.

About freeing memory, you are right! I'll change the program as suggested. Thanks!

**Comment by coisme** [comment]
Hi @nuertey , I built on Ubuntu 18.04 and run the binary on NUCLEO_F767ZI target. However, it ran successfully.

```
$ uname -a
Linux XXXXXX 4.15.0-42-generic #45-Ubuntu SMP Thu Nov 15 19:32:57 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ ~/gcc-arm-none-eabi/bin/arm-none-eabi-gcc --version
arm-none-eabi-gcc (GNU Tools for Arm Embedded Processors 7-2018-q2-update) 7.3.1 20180622 (release) [ARM/embedded-7-branch revision 261907]
```

```
$ mbed ls
[mbed] Working path "/home/osakoi01/mbed/Hello-TLSSocket" (program)
Hello-TLSSocket (#35e7003e86b3)
|- TLSSocket (#723094a6ff84)
|- mbed-os (#6f338f8915d2)
`- ntp-client (#72a3f00ca7c1)
```

There are two difference:
* I use Ubuntu 18.04, you use 16.04.
* When `mbed ls`, You see message `[mbed] Working path "~/Workspace/Hello-TLSSocket" (library)`, but I don't.

Can you try with importing the project from GitHub in a new directory?

**Comment by nuertey** [comment]
Hi @coisme ,
I think we can mark this issue as resolved. All indications point at it being an issue/quirk with my network connection/ISP. I don't think that the mbed working path or Ubuntu/Linux version would matter in this case. I am busy trying out your Mbed-to-IBM-Watson-IoT application and the AWS one so will not be able to try out your suggestion at the moment. Just close this issue. I think we have resolved it.

**Comment by coisme** [comment]
@nuertey Ok. I'll dig in when it found again. Thanks.
